
var __cov_eqxW8VZSmKXaWp_lH5ZUjA = (Function('return this'))();
if (!__cov_eqxW8VZSmKXaWp_lH5ZUjA.$$cov_1535201918722$$) { __cov_eqxW8VZSmKXaWp_lH5ZUjA.$$cov_1535201918722$$ = {}; }
__cov_eqxW8VZSmKXaWp_lH5ZUjA = __cov_eqxW8VZSmKXaWp_lH5ZUjA.$$cov_1535201918722$$;
if (!(__cov_eqxW8VZSmKXaWp_lH5ZUjA['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/bullet.js'])) {
   __cov_eqxW8VZSmKXaWp_lH5ZUjA['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/bullet.js'] = {"path":"/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/bullet.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":1,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0,"17":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"Bullet","line":10,"loc":{"start":{"line":10,"column":0},"end":{"line":10,"column":59}}},"2":{"name":"destroy","line":17,"loc":{"start":{"line":17,"column":27},"end":{"line":17,"column":46}}},"3":{"name":"draw","line":21,"loc":{"start":{"line":21,"column":24},"end":{"line":21,"column":48}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":37}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":47}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":39}},"4":{"start":{"line":6,"column":0},"end":{"line":6,"column":53}},"5":{"start":{"line":7,"column":0},"end":{"line":7,"column":57}},"6":{"start":{"line":8,"column":0},"end":{"line":8,"column":38}},"7":{"start":{"line":10,"column":0},"end":{"line":15,"column":1}},"8":{"start":{"line":12,"column":2},"end":{"line":12,"column":59}},"9":{"start":{"line":12,"column":31},"end":{"line":12,"column":59}},"10":{"start":{"line":13,"column":2},"end":{"line":13,"column":41}},"11":{"start":{"line":14,"column":2},"end":{"line":14,"column":63}},"12":{"start":{"line":17,"column":0},"end":{"line":19,"column":2}},"13":{"start":{"line":18,"column":2},"end":{"line":18,"column":19}},"14":{"start":{"line":21,"column":0},"end":{"line":25,"column":2}},"15":{"start":{"line":22,"column":2},"end":{"line":24,"column":3}},"16":{"start":{"line":23,"column":4},"end":{"line":23,"column":49}},"17":{"start":{"line":27,"column":0},"end":{"line":27,"column":24}}},"branchMap":{"1":{"line":12,"type":"if","locations":[{"start":{"line":12,"column":2},"end":{"line":12,"column":2}},{"start":{"line":12,"column":2},"end":{"line":12,"column":2}}]},"2":{"line":22,"type":"if","locations":[{"start":{"line":22,"column":2},"end":{"line":22,"column":2}},{"start":{"line":22,"column":2},"end":{"line":22,"column":2}}]}}};
}
__cov_eqxW8VZSmKXaWp_lH5ZUjA = __cov_eqxW8VZSmKXaWp_lH5ZUjA['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/bullet.js'];
__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['1']++;var FillRect=require('./fillRect');__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['2']++;var MovableObject=require('./movableObject');__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['3']++;var directions=require('../globals');__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['4']++;Bullet.prototype=Object.create(FillRect.prototype);__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['5']++;Object.assign(Bullet.prototype,MovableObject.prototype);__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['6']++;Bullet.prototype.constructor=Bullet;function Bullet(x,y,w,h,color,speed,step,direction){__cov_eqxW8VZSmKXaWp_lH5ZUjA.f['1']++;__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['8']++;if(direction===undefined){__cov_eqxW8VZSmKXaWp_lH5ZUjA.b['1'][0]++;__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['9']++;direction=directions.EAST;}else{__cov_eqxW8VZSmKXaWp_lH5ZUjA.b['1'][1]++;}__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['10']++;FillRect.call(this,x,y,w,h,color);__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['11']++;MovableObject.call(this,x,y,speed,direction,step,step);}__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['12']++;Bullet.prototype.destroy=function destroy(){__cov_eqxW8VZSmKXaWp_lH5ZUjA.f['2']++;__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['13']++;this.dead=true;};__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['14']++;Bullet.prototype.draw=function draw(renderer){__cov_eqxW8VZSmKXaWp_lH5ZUjA.f['3']++;__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['15']++;if(!this.dead){__cov_eqxW8VZSmKXaWp_lH5ZUjA.b['2'][0]++;__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['16']++;FillRect.prototype.draw.call(this,renderer);}else{__cov_eqxW8VZSmKXaWp_lH5ZUjA.b['2'][1]++;}};__cov_eqxW8VZSmKXaWp_lH5ZUjA.s['17']++;module.exports=Bullet;
