
var __cov_pCTlZjtjrUK84$sWmGn$FQ = (Function('return this'))();
if (!__cov_pCTlZjtjrUK84$sWmGn$FQ.$$cov_1535201918722$$) { __cov_pCTlZjtjrUK84$sWmGn$FQ.$$cov_1535201918722$$ = {}; }
__cov_pCTlZjtjrUK84$sWmGn$FQ = __cov_pCTlZjtjrUK84$sWmGn$FQ.$$cov_1535201918722$$;
if (!(__cov_pCTlZjtjrUK84$sWmGn$FQ['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/index.js'])) {
   __cov_pCTlZjtjrUK84$sWmGn$FQ['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/index.js'] = {"path":"/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/index.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{},"fnMap":{},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":39}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":33}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":37}},"4":{"start":{"line":4,"column":0},"end":{"line":4,"column":41}},"5":{"start":{"line":5,"column":0},"end":{"line":5,"column":47}},"6":{"start":{"line":6,"column":0},"end":{"line":6,"column":47}},"7":{"start":{"line":7,"column":0},"end":{"line":7,"column":33}},"8":{"start":{"line":9,"column":0},"end":{"line":17,"column":2}}},"branchMap":{}};
}
__cov_pCTlZjtjrUK84$sWmGn$FQ = __cov_pCTlZjtjrUK84$sWmGn$FQ['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/index.js'];
__cov_pCTlZjtjrUK84$sWmGn$FQ.s['1']++;var Rectangle=require('./rectangle');__cov_pCTlZjtjrUK84$sWmGn$FQ.s['2']++;var Sprite=require('./sprite');__cov_pCTlZjtjrUK84$sWmGn$FQ.s['3']++;var FillRect=require('./fillRect');__cov_pCTlZjtjrUK84$sWmGn$FQ.s['4']++;var StrokeRect=require('./strokeRect');__cov_pCTlZjtjrUK84$sWmGn$FQ.s['5']++;var MovableObject=require('./movableObject');__cov_pCTlZjtjrUK84$sWmGn$FQ.s['6']++;var MovableSprite=require('./movableSprite');__cov_pCTlZjtjrUK84$sWmGn$FQ.s['7']++;var Bullet=require('./bullet');__cov_pCTlZjtjrUK84$sWmGn$FQ.s['8']++;module.exports={Rectangle:Rectangle,Sprite:Sprite,FillRect:FillRect,StrokeRect:StrokeRect,MovableObject:MovableObject,MovableSprite:MovableSprite,Bullet:Bullet};
