
var __cov_AbeWG8yHrC7KktrWXp1iZw = (Function('return this'))();
if (!__cov_AbeWG8yHrC7KktrWXp1iZw.$$cov_1535201918722$$) { __cov_AbeWG8yHrC7KktrWXp1iZw.$$cov_1535201918722$$ = {}; }
__cov_AbeWG8yHrC7KktrWXp1iZw = __cov_AbeWG8yHrC7KktrWXp1iZw.$$cov_1535201918722$$;
if (!(__cov_AbeWG8yHrC7KktrWXp1iZw['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/movableSprite.js'])) {
   __cov_AbeWG8yHrC7KktrWXp1iZw['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/movableSprite.js'] = {"path":"/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/movableSprite.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":1,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"MovableSprite","line":8,"loc":{"start":{"line":8,"column":0},"end":{"line":8,"column":86}}},"2":{"name":"draw","line":13,"loc":{"start":{"line":13,"column":31},"end":{"line":13,"column":55}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":33}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":47}},"3":{"start":{"line":4,"column":0},"end":{"line":4,"column":58}},"4":{"start":{"line":5,"column":0},"end":{"line":5,"column":64}},"5":{"start":{"line":6,"column":0},"end":{"line":6,"column":52}},"6":{"start":{"line":8,"column":0},"end":{"line":11,"column":1}},"7":{"start":{"line":9,"column":2},"end":{"line":9,"column":59}},"8":{"start":{"line":10,"column":2},"end":{"line":10,"column":63}},"9":{"start":{"line":13,"column":0},"end":{"line":19,"column":2}},"10":{"start":{"line":14,"column":2},"end":{"line":14,"column":18}},"11":{"start":{"line":15,"column":2},"end":{"line":15,"column":63}},"12":{"start":{"line":16,"column":2},"end":{"line":16,"column":49}},"13":{"start":{"line":17,"column":2},"end":{"line":17,"column":75}},"14":{"start":{"line":18,"column":2},"end":{"line":18,"column":21}},"15":{"start":{"line":21,"column":0},"end":{"line":21,"column":31}}},"branchMap":{}};
}
__cov_AbeWG8yHrC7KktrWXp1iZw = __cov_AbeWG8yHrC7KktrWXp1iZw['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/movableSprite.js'];
__cov_AbeWG8yHrC7KktrWXp1iZw.s['1']++;var Sprite=require('./sprite');__cov_AbeWG8yHrC7KktrWXp1iZw.s['2']++;var MovableObject=require('./movableObject');__cov_AbeWG8yHrC7KktrWXp1iZw.s['3']++;MovableSprite.prototype=Object.create(Sprite.prototype);__cov_AbeWG8yHrC7KktrWXp1iZw.s['4']++;Object.assign(MovableSprite.prototype,MovableObject.prototype);__cov_AbeWG8yHrC7KktrWXp1iZw.s['5']++;MovableSprite.prototype.constructor=MovableSprite;function MovableSprite(x,y,w,h,imagePath,onLoadCallback,speed,step,direction){__cov_AbeWG8yHrC7KktrWXp1iZw.f['1']++;__cov_AbeWG8yHrC7KktrWXp1iZw.s['7']++;Sprite.call(this,x,y,w,h,imagePath,onLoadCallback);__cov_AbeWG8yHrC7KktrWXp1iZw.s['8']++;MovableObject.call(this,x,y,speed,direction,step,step);}__cov_AbeWG8yHrC7KktrWXp1iZw.s['9']++;MovableSprite.prototype.draw=function draw(renderer){__cov_AbeWG8yHrC7KktrWXp1iZw.f['2']++;__cov_AbeWG8yHrC7KktrWXp1iZw.s['10']++;renderer.save();__cov_AbeWG8yHrC7KktrWXp1iZw.s['11']++;renderer.translate(this.x+this.w/2,this.y+this.h/2);__cov_AbeWG8yHrC7KktrWXp1iZw.s['12']++;renderer.rotate(this.getAngle(this.direction));__cov_AbeWG8yHrC7KktrWXp1iZw.s['13']++;renderer.drawImage(this.image,-this.w/2,-this.h/2,this.w,this.h);__cov_AbeWG8yHrC7KktrWXp1iZw.s['14']++;renderer.restore();};__cov_AbeWG8yHrC7KktrWXp1iZw.s['15']++;module.exports=MovableSprite;
