
var __cov_kO0gcwxuIiMcjkZsjJUl3g = (Function('return this'))();
if (!__cov_kO0gcwxuIiMcjkZsjJUl3g.$$cov_1535201918722$$) { __cov_kO0gcwxuIiMcjkZsjJUl3g.$$cov_1535201918722$$ = {}; }
__cov_kO0gcwxuIiMcjkZsjJUl3g = __cov_kO0gcwxuIiMcjkZsjJUl3g.$$cov_1535201918722$$;
if (!(__cov_kO0gcwxuIiMcjkZsjJUl3g['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/rectangle.js'])) {
   __cov_kO0gcwxuIiMcjkZsjJUl3g['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/rectangle.js'] = {"path":"/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/rectangle.js","s":{"1":1,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0,"17":0,"18":0,"19":0},"b":{"1":[0,0],"2":[0,0,0,0],"3":[0,0]},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"Rectangle","line":1,"loc":{"start":{"line":1,"column":0},"end":{"line":1,"column":31}}},"2":{"name":"overlap","line":19,"loc":{"start":{"line":19,"column":30},"end":{"line":19,"column":70}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":12,"column":1}},"2":{"start":{"line":2,"column":2},"end":{"line":2,"column":13}},"3":{"start":{"line":3,"column":2},"end":{"line":3,"column":13}},"4":{"start":{"line":4,"column":2},"end":{"line":4,"column":13}},"5":{"start":{"line":5,"column":2},"end":{"line":5,"column":13}},"6":{"start":{"line":6,"column":2},"end":{"line":6,"column":15}},"7":{"start":{"line":7,"column":2},"end":{"line":7,"column":16}},"8":{"start":{"line":8,"column":2},"end":{"line":8,"column":21}},"9":{"start":{"line":9,"column":2},"end":{"line":9,"column":22}},"10":{"start":{"line":10,"column":2},"end":{"line":10,"column":29}},"11":{"start":{"line":11,"column":2},"end":{"line":11,"column":29}},"12":{"start":{"line":19,"column":0},"end":{"line":31,"column":2}},"13":{"start":{"line":20,"column":2},"end":{"line":29,"column":3}},"14":{"start":{"line":25,"column":4},"end":{"line":27,"column":5}},"15":{"start":{"line":26,"column":6},"end":{"line":26,"column":17}},"16":{"start":{"line":28,"column":4},"end":{"line":28,"column":16}},"17":{"start":{"line":30,"column":2},"end":{"line":30,"column":15}},"18":{"start":{"line":33,"column":0},"end":{"line":33,"column":43}},"19":{"start":{"line":35,"column":0},"end":{"line":35,"column":27}}},"branchMap":{"1":{"line":20,"type":"if","locations":[{"start":{"line":20,"column":2},"end":{"line":20,"column":2}},{"start":{"line":20,"column":2},"end":{"line":20,"column":2}}]},"2":{"line":20,"type":"binary-expr","locations":[{"start":{"line":20,"column":6},"end":{"line":20,"column":47}},{"start":{"line":21,"column":7},"end":{"line":21,"column":41}},{"start":{"line":22,"column":7},"end":{"line":22,"column":48}},{"start":{"line":23,"column":7},"end":{"line":23,"column":41}}]},"3":{"line":25,"type":"if","locations":[{"start":{"line":25,"column":4},"end":{"line":25,"column":4}},{"start":{"line":25,"column":4},"end":{"line":25,"column":4}}]}}};
}
__cov_kO0gcwxuIiMcjkZsjJUl3g = __cov_kO0gcwxuIiMcjkZsjJUl3g['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/rectangle.js'];
function Rectangle(x,y,w,h){__cov_kO0gcwxuIiMcjkZsjJUl3g.f['1']++;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['2']++;this.w=w;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['3']++;this.h=h;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['4']++;this.x=x;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['5']++;this.y=y;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['6']++;this.top=y;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['7']++;this.left=x;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['8']++;this.right=x+w;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['9']++;this.bottom=y+h;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['10']++;this.centerX=x+w*0.5;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['11']++;this.centerY=y+h*0.5;}__cov_kO0gcwxuIiMcjkZsjJUl3g.s['12']++;Rectangle.prototype.overlap=function overlap(anotherRect,callback){__cov_kO0gcwxuIiMcjkZsjJUl3g.f['2']++;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['13']++;if((__cov_kO0gcwxuIiMcjkZsjJUl3g.b['2'][0]++,this.x<=anotherRect.x+anotherRect.w)&&(__cov_kO0gcwxuIiMcjkZsjJUl3g.b['2'][1]++,anotherRect.x<=this.x+this.w)&&(__cov_kO0gcwxuIiMcjkZsjJUl3g.b['2'][2]++,this.y<=anotherRect.y+anotherRect.h)&&(__cov_kO0gcwxuIiMcjkZsjJUl3g.b['2'][3]++,anotherRect.y<=this.y+this.h)){__cov_kO0gcwxuIiMcjkZsjJUl3g.b['1'][0]++;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['14']++;if(typeof callback==='function'){__cov_kO0gcwxuIiMcjkZsjJUl3g.b['3'][0]++;__cov_kO0gcwxuIiMcjkZsjJUl3g.s['15']++;callback();}else{__cov_kO0gcwxuIiMcjkZsjJUl3g.b['3'][1]++;}__cov_kO0gcwxuIiMcjkZsjJUl3g.s['16']++;return true;}else{__cov_kO0gcwxuIiMcjkZsjJUl3g.b['1'][1]++;}__cov_kO0gcwxuIiMcjkZsjJUl3g.s['17']++;return false;};__cov_kO0gcwxuIiMcjkZsjJUl3g.s['18']++;Rectangle.ZERO=new Rectangle(0,0,0,0);__cov_kO0gcwxuIiMcjkZsjJUl3g.s['19']++;module.exports=Rectangle;
