
var __cov_oYUUbrXEirARKR2V8vb_PQ = (Function('return this'))();
if (!__cov_oYUUbrXEirARKR2V8vb_PQ.$$cov_1535201918722$$) { __cov_oYUUbrXEirARKR2V8vb_PQ.$$cov_1535201918722$$ = {}; }
__cov_oYUUbrXEirARKR2V8vb_PQ = __cov_oYUUbrXEirARKR2V8vb_PQ.$$cov_1535201918722$$;
if (!(__cov_oYUUbrXEirARKR2V8vb_PQ['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/strokeRect.js'])) {
   __cov_oYUUbrXEirARKR2V8vb_PQ['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/strokeRect.js'] = {"path":"/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/strokeRect.js","s":{"1":0,"2":1,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"StrokeRect","line":2,"loc":{"start":{"line":2,"column":0},"end":{"line":2,"column":39}}},"2":{"name":"draw","line":9,"loc":{"start":{"line":9,"column":28},"end":{"line":9,"column":52}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":39}},"2":{"start":{"line":2,"column":0},"end":{"line":5,"column":1}},"3":{"start":{"line":3,"column":2},"end":{"line":3,"column":35}},"4":{"start":{"line":4,"column":2},"end":{"line":4,"column":21}},"5":{"start":{"line":6,"column":0},"end":{"line":6,"column":58}},"6":{"start":{"line":7,"column":0},"end":{"line":7,"column":46}},"7":{"start":{"line":9,"column":0},"end":{"line":15,"column":2}},"8":{"start":{"line":10,"column":2},"end":{"line":10,"column":36}},"9":{"start":{"line":11,"column":2},"end":{"line":11,"column":21}},"10":{"start":{"line":12,"column":2},"end":{"line":12,"column":31}},"11":{"start":{"line":13,"column":2},"end":{"line":13,"column":55}},"12":{"start":{"line":14,"column":2},"end":{"line":14,"column":27}},"13":{"start":{"line":17,"column":0},"end":{"line":17,"column":28}}},"branchMap":{}};
}
__cov_oYUUbrXEirARKR2V8vb_PQ = __cov_oYUUbrXEirARKR2V8vb_PQ['/home/azizou/Projects/gameEngine/battleCity/src/gameObjects/strokeRect.js'];
__cov_oYUUbrXEirARKR2V8vb_PQ.s['1']++;var Rectangle=require('./rectangle');function StrokeRect(x,y,w,h,color){__cov_oYUUbrXEirARKR2V8vb_PQ.f['1']++;__cov_oYUUbrXEirARKR2V8vb_PQ.s['3']++;Rectangle.call(this,x,y,w,h);__cov_oYUUbrXEirARKR2V8vb_PQ.s['4']++;this.color=color;}__cov_oYUUbrXEirARKR2V8vb_PQ.s['5']++;StrokeRect.prototype=Object.create(Rectangle.prototype);__cov_oYUUbrXEirARKR2V8vb_PQ.s['6']++;StrokeRect.prototype.constructor=StrokeRect;__cov_oYUUbrXEirARKR2V8vb_PQ.s['7']++;StrokeRect.prototype.draw=function draw(renderer){__cov_oYUUbrXEirARKR2V8vb_PQ.f['2']++;__cov_oYUUbrXEirARKR2V8vb_PQ.s['8']++;var sStyle=renderer.strokeStyle;__cov_oYUUbrXEirARKR2V8vb_PQ.s['9']++;var ctx=renderer;__cov_oYUUbrXEirARKR2V8vb_PQ.s['10']++;ctx.strokeStyle=this.color;__cov_oYUUbrXEirARKR2V8vb_PQ.s['11']++;renderer.strokeStyle(this.x,this.y,this.w,this.h);__cov_oYUUbrXEirARKR2V8vb_PQ.s['12']++;ctx.strokeStyle=sStyle;};__cov_oYUUbrXEirARKR2V8vb_PQ.s['13']++;module.exports=StrokeRect;
